config/routes.rb
Rails.application.routes.draw do
  
  root "movies#index"
  
  resources :movies do 
    resources :reviews
  end
  
  resources :users
  get "signup" => "users#new"

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many :reviews, dependent: :destroy

  validates :title, :released_on, :duration, presence: true
  validates :description, length: { minimum: 25 }
  validates :total_gross, numericality: { greate_than_or_equal_to: 0 }
  validates :image_file_name, format: {
                                        with: /\w+\.(jpg|png)\z/i,
                                        message: "must be a JPG or PNG image"
                                      }
  RATINGS = %w(G PG PG-13 R NC-17)
  validates :rating, inclusion: { in: RATINGS }                                    
                                  

  def flop?
    total_gross.blank? || total_gross < 225_000_000
  end

  def self.released
    where("released_on < ?", Time.now).order("released_on desc")
  end

  def average_stars
    reviews.average(:stars) || 0.0
  end
  
  def average_stars_as_percent
    (self.average_stars / 5.0) * 100
  end
  
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie

  validates :name, presence: true
  validates :comment, length: { minimum: 4 }
  
  STARS = [1, 2, 3, 4, 5]

  validates :stars, inclusion: { in: STARS, message: "must be between 1 and 5" }

  def stars_as_percent
    (stars / 5.0) * 100.0
  end

  

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: true }
  validates :password, length: { minimum: 10, allow_blank: true }
  validates :username, presence: true, format: { with: /\A[A-Z0-9]+\z/i },
            uniqueness: { case_sensitive: false }
            

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user



  def current_user_admin?
    current_user && current_user.admin?
  end

  helper_method :current_user_admin?

  
  
  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?

  
  
  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "Please, sign in first!"
    end
  end

  def require_admim
    unless current_user_admin?
      redirect_to movies_url, alert: "Unaothorized access!"
    end
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movie = Movie.released
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie, notice: "Movie updated!"
    else
      render :edit, status: :unprocessable_entity
    end    
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Created movie!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path, status: :see_other, alert: "Movie successfully deleted!"
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :rating, :total_gross, :description, :released_on,        :director, :duration, :image_file_name)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_movie

  def index
    @reviews = @movie.reviews
  end

  def new
    @review = @movie.reviews.new
  end

  def create
    @review = @movie.reviews.new(review_params)
  
    if @review.save
      redirect_to movie_reviews_path(@movie), notice: "Thanks for your review!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:name, :comment, :stars)
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to (session[:intended_url] || user), notice: "Welcome back, #{user.name}"
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_url, status: :see_other, notice: "You're now signed out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]
 
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update 
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
      
    else
      render :edit, status: :unprocessable_entity
    end

  end
  
  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to movies_url, status: :see_other, alert: "Account successfully deleted"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :username)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to events_url unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/movies_helper.rb
module MoviesHelper

  def total_gross(movie)
    if movie.flop?
      "Flop!"
    else
      number_to_currency(movie.total_gross, precision: 0)
    end
  end

  def year_of(movie)
    movie.released_on.strftime("%Y")
  end

  def average_stars(movie)
    if movie.average_stars.zero?
      content_tag(:strong, "No reviews")
    else
      "*" * movie.average_stars.round
    end
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
  <footer>
    <p>
      Copyright &copy; <%= Time.now.year %>
      <%= link_to "The Pragmatic Studio", "https://pragmaticstudio.com" %>
    </p>
  </footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
      <%= link_to image_tag("logo.png"), root_path %>
    <ul class="left" >
      <li>
        <%= link_to "All movies", movies_path %>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Account Settings", edit_user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Sign Out", session_path,
                      data: { turbo_method: :delete }, class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign in", signin_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render "layouts/header" %>

    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for( movie ) do |f| %>

  <%= render "shared/errors", object: movie %>



  <div>
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true %>
  </div>  
  
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 7 %>
  </div>
  
  <div>
    <%= f.label :rating %>
    <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
  </div>

  <div>
    <%= f.label :director %>
    <%= f.text_field :director %>
  </div>

  <div>
    <%= f.label :duration %>
    <%= f.text_field :duration %>
  </div>

  <div>
    <%= f.label :image_file_name %>
    <%= f.text_field :image_file_name %>
  </div>

  <div>
    <%= f.label :released_on %>
    <%= f.date_field :released_on, {class: "date" }%>
  </div>
  
  <div>
    <%= f.label :total_gross %>
    <%= f.number_field :total_gross %>
  </div>

  <div>
    <%= f.submit %>
  </div>    

<% end %>

app/views/movies/edit.html.erb
<h1>Editing <%= @movie.title %></h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<% @movie.each do |movie|%>
  <section class="movie">
    <div class="summary">
      <h2><%= link_to movie.title, movie_path(movie) %></h2> 
      <h3><%= total_gross(movie) %></h3>
        <span class="stars">
          <%= render "shared/stars", percent: movie.average_stars_as_percent %>
        </span>
      <p><%= truncate(movie.description, lenght: 150, separator: ' ') %></p>
      <p><%= year_of(movie) %></p>
    </div>
  </section>
<% end %>

<% if current_user_admin? %>
  <section>
    <%= link_to "Add New Movie", new_movie_path, class: "button" %>
  </section>
<% end %>

app/views/movies/new.html.erb
<h1>Create a New Movie </h1>

<%= render "form", movie: @movie %>, 

app/views/movies/show.html.erb
<section class="details">
  <div class="details">
    <h1><%= @movie.title %></h1>
    <h2><%= year_of(@movie) %> &bull; <%= @movie.rating %></h2>
    <div class="reviews">
      <%= render "shared/stars", percent: @movie.average_stars_as_percent %>
      <%= link_to pluralize(@movie.reviews.size, 'review'), movie_reviews_path(@movie) %>
    </div>
    <p><%= @movie.description %></p>
    <table>
      <tr>
        <th> Total Gross: </th>
        <td><%= total_gross(@movie) %></td>
      </tr>
    </table>
    <%= link_to "Write review", new_movie_review_path(@movie), class: "review" %>
  </div>
</section>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
    <%= link_to "Delete", movie_path(@movie), class: "button",
                          data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  </section>
<% end %>

    
 

app/views/reviews/_form.html.erb
<%= form_with(model: [@movie, @review]) do |f| %>

  <%= render "shared/errors", object: @review %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

 <%= f.label :stars %>
  <% Review::STARS.each do |star| %>
    <span class="star">
      <%= f.radio_button :stars, star %>
      <%= label_tag star %>
    </span>
  <% end %>
  
  <%= f.label :comment %>
  <%= f.text_area :comment, placeholder: "What did you think?" %>

  <%= f.submit "Post Review" %>
  
<% end %>

app/views/reviews/index.html.erb
<h1>Review for <%= link_to @movie.title, @movie %></h1>
<ul class="review" >
  <% @reviews.each do |review| %>
    <li>
      <%= render "shared/stars", percent: review.stars_as_percent %>
    <p>
      <%= review.name %>
      <span class="date">
        <%= time_ago_in_words(review.created_at) %> ago
      </span>
    </p>
    <p><%= review.comment %></p>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>New review for <%= link_to @movie.title, @movie%></h1>

<%= render "form" %>

app/views/shared/_errors.html.erb
  <% if object.errors.any? %>
    <section class="errors">
      <h2>
        Oops! Your form could not be saved.
      </h2>
      <h3>
        Please correct the following
        <%= pluralize(object.errors.size, "error") %>:
      </h3>
      <ul>
        <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </section>
  <% end %>

app/views/shared/_stars.html.erb
<div class="star-rating">
  <div class="back-stars">
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <div class="front-stars" style="width: <%= percent %>%">
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with( model: user) do |f| %>

  <%= render "shared/errors", object: user %>
  
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "Alphanumeric characters only!" %>

  <%= f.label :email %>
  <%= f.email_field :email, autofocus: true, required: true %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
    <%= f.submit "Create Account" %>
  <% else %>
    <%= f.submit "Update Account" %>
  <% end %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> created
      <%= time_ago_in_words(user.created_at) %> ago 
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
  <h1><%= @user.name %></h1>
  <h2><%= @user.username %></h2>
  <h2><%= mail_to(@user.email) %></h2>
  <h3>Member since</h3>
  <p>
    <%= @user.created_at.strftime("%B %Y")%>
  </p>
  <% if current_user?(@user) %>
    <div class="actions">
      <%= link_to "Edit Account", edit_user_path(@user), class: "button edit" %>
      <%= link_to "Delete Account", @user, class: "button delete", 
          data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </div>
  <% end %>
</section>